spring:
  datasource:
    url: jdbc:h2:mem:maindb

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    command:
      version:
        enabled: false

  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none

    show-sql: true

  data:
    mongodb:
      database: main_db
      host: localhost
      port: 27017

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.hw.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
