spring:
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: true
  output:
    ansi:
      enabled: always

test:
  rightAnswersCountToPass: 3
  locale: fr-FR
  fileNameByLocaleTag:
    en-US: questions.csv
    ru-RU: questions_ru.csv
    fr-FR: questions_fr.csv